// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package sbs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IdAndCategory-1]
	_ = x[SurfacePosition-2]
	_ = x[AirbornePosition-3]
	_ = x[AirborneVelocity-4]
	_ = x[Alt-5]
	_ = x[ID-6]
	_ = x[AitToAir-7]
	_ = x[AllCallReply-8]
}

const _MessageType_name = "IdAndCategorySurfacePositionAirbornePositionAirborneVelocityAltIDAitToAirAllCallReply"

var _MessageType_index = [...]uint8{0, 13, 28, 44, 60, 63, 65, 73, 85}

func (i MessageType) String() string {
	i -= 1
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
